org: acolytec3
app: avatar-scraper
service: avatar-star

plugins:
  - serverless-plugin-typescript
  - serverless-s3-local
  - serverless-offline-env
  - serverless-offline
  - serverless-prune-plugin

custom:
  serverless-offline-env:
    path: .env
  serverless-offline:
    noPrependStageInUrl: true
    noTimeout: true
    port: 3000
    host: localhost
  s3:
    port: 8000
    directory: /tmp
  prune:
    automatic: true
    number: 3
  bucket: ${file(env.${opt:stage, self:provider.stage}.json):S3BUCKETNAME}
  
provider:
  name: aws
  runtime: nodejs12.x
  environment: 
    checkByDate: 10000000
    imageWidth: 48
    s3Endpoint: ${file(env.${opt:stage, self:provider.stage}.json):S3ENDPOINT}
    s3AccessKey: ${file(env.${opt:stage, self:provider.stage}.json):S3ACCESSKEYID}
    s3SecretAccessKey: ${file(env.${opt:stage, self:provider.stage}.json):S3SECRETACCESSKEY}
  iamRoleStatements:
  - Effect: Allow
    Action:
      - s3:PutObject
      - s3:GetObject
      - s3:ListObjects
    Resource: 
      - "arn:aws:s3:::${self:custom.bucket}.twitter/*"
      - "arn:aws:s3:::${self:custom.bucket}.substack/*"
functions:
  twitter:
    handler: handlers/twitter.default
    environment:
      twitterBearerToken: ${file(env.${opt:stage, self:provider.stage}.json):TWITTER_BEARER_TOKEN}
      bucket: ${self:custom.bucket}.twitter
      bucketKeyTemplate: ${self:custom.bucket}.twitter/twitter/
    events:
      - http:
          path: twitter/{id}
          method: get
          request:
            parameters:
              paths:
                id: true 
      - s3:
          bucket: ${self:custom.bucket}.twitter

  substack:
    handler: handlers/substack.default
    environment:
      bucket: ${self:custom.bucket}.substack
      bucketKeyTemplate: ${self:custom.bucket}.substack/substack/
    events:
      - http:
          path: substack/{id}
          method: get
          request:
            parameters:
              paths:
                id: true 
      - s3:
          bucket: ${self:custom.bucket}.substack

