org: acolytec3
app: avatar-scraper
service: avatar-star

plugins:
  - serverless-plugin-typescript
  - serverless-s3-local
  - serverless-offline-env
  - serverless-offline
  - serverless-prune-plugin

custom:
  serverless-offline-env:
    path: .env
  serverless-offline:
    noPrependStageInUrl: true
    noTimeout: true
    port: 3000
    host: localhost
  s3:
    port: 8000
    directory: /tmp
  prune:
    automatic: true
    number: 3
  
provider:
  name: aws
  runtime: nodejs12.x
  environment: 
    checkByDate: 10000000
    imageWidth: 48
    s3Endpoint: ${file(env.${opt:stage, self:provider.stage}.json):S3ENDPOINT}
    s3AccessKey: ${file(env.${opt:stage, self:provider.stage}.json):S3ACCESSKEYID}
    s3SecretAccessKey: ${file(env.${opt:stage, self:provider.stage}.json):S3SECRETACCESSKEY}
    s3Bucket: ${file(env.${opt:stage, self:provider.stage}.json):S3BUCKETNAME}
    
functions:
  twitter:
    handler: handlers/twitter.default
    environment:
      twitterBearerToken: ${file(env.${opt:stage, self:provider.stage}.json):TWITTER_BEARER_TOKEN}
    events:
      - http:
          path: twitter/{id}
          method: get
          request:
            parameters:
              paths:
                id: true 

  substack:
    handler: handlers/substack.default
    events:
      - http:
          path: substack/{id}
          method: get
          request:
            parameters:
              paths:
                id: true 

